#!/usr/bin/env python3
import os
import sys
import shutil
import subprocess

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 encode_vfr.py <path_to_capture_folder>")
        sys.exit(1)

    target_dir = sys.argv[1].rstrip("/")
    mjpeg_file = os.path.join(target_dir, "video.mjpeg")
    ts_file = os.path.join(target_dir, "timestamps.txt")
    frames_dir = os.path.join(target_dir, "frames")
    output_mp4 = os.path.join(target_dir, "output_vfr.mp4")

    # 1. Validate inputs
    if not os.path.exists(mjpeg_file) or not os.path.exists(ts_file):
        print(f"[!] Error: Could not find video.mjpeg or timestamps.txt in '{target_dir}'")
        sys.exit(1)

    # 2. Setup frames directory
    if os.path.exists(frames_dir):
        print(f"[*] Cleaning up old frames directory...")
        shutil.rmtree(frames_dir)
    os.makedirs(frames_dir)

    # 3. Extract frames from the raw MJPEG
    print(f"\n[*] Step 1/3: Extracting frames from {mjpeg_file}...")
    extract_cmd = [
        "ffmpeg", "-i", mjpeg_file,
        "-q:v", "2",  # Keep highest JPEG quality
        os.path.join(frames_dir, "frame_%05d.jpg")
    ]
    subprocess.run(extract_cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    # 4. Read timestamps and apply to filesystem properties
    print(f"[*] Step 2/3: Applying V4L2 timestamps to frame files...")
    with open(ts_file, 'r') as f:
        v4l2_timestamps = [float(line.strip()) for line in f if line.strip()]

    processed_count = 0
    for i, t in enumerate(v4l2_timestamps):
        # ffmpeg %05d starts at 1, so index is i+1
        filename = os.path.join(frames_dir, f"frame_{i+1:05d}.jpg")
        if os.path.exists(filename):
            # Set modification time (mtime) directly to the V4L2 hardware offset
            os.utime(filename, (t, t))
            processed_count += 1
        else:
            print(f"Warning: Expected {filename} but it wasn't generated by FFmpeg.")

    print(f"    -> Modified timestamps for {processed_count} frames.")

    # 5. Compile cleanly to a VFR MP4 using the filesystem times
    print(f"[*] Step 3/3: Encoding to VFR MP4...")
    encode_cmd = [
        "ffmpeg", "-y",
        "-f", "image2",
        "-ts_from_file", "2",  # Use file modification times as timestamps
        "-i", os.path.join(frames_dir, "frame_%05d.jpg"),
        "-vsync", "vfr",       # Variable frame rate mode (modern ffmpeg also accepts -fps_mode vfr)
        "-c:v", "libx264",
        "-crf", "18",          # High quality encode
        output_mp4
    ]
    
    result = subprocess.run(encode_cmd)

    if result.returncode == 0:
        print(f"\n[+] Success! VFR video saved to: {output_mp4}")
        # Optional: Clean up frames folder to save space
        # shutil.rmtree(frames_dir) 
    else:
        print(f"\n[!] Encoding failed. Check FFmpeg output above.")

if __name__ == "__main__":
    main()